[book]
authors = ["Domtron Vox"]
language = "en"
multilingual = false
src = "src"
title = "Building A Self-sufficient, Christian Intentional Community"
description = "Information covering the creation of a small scale self-sufficent, intentionally created community."

[build]
build-dir = "build"
create-missing = false
use-default-preprocessors = true  

[output.html]
default-theme = "navy"
additional-css = []
git-repository-url = ""
#cname = "self-sufficiency.bendhacknslash.com"

#[preprocessor.graphviz]
#command = "mdbook-graphviz"
#output-to-file = false
