[book]
authors = ["Domtron Vox"]
language = "en"
multilingual = false
src = "src"
title = "Reaserch Notes"
description = "Notes documenting various topics I run across that looks interesting."

[build]
build-dir = "build"
create-missing = false
use-default-preprocessors = true  

[output.html]
default-theme = "navy"
additional-css = []
